version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: project-management:latest
    container_name: project-management
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    restart: always
